version: '3.7'
services:
  postgres:
    image: postgres:13
    container_name: postgres_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  minio:
    image: minio/minio:latest
    container_name: minio
    environment:
      MINIO_ROOT_USER: ${MINIO_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_PASSWORD}
    volumes:
      - minio_data:/data
    ports:
      - "9001:9001"
    command: server /data --console-address ":9001"
    restart: always

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app_service
    ports:
      - "5000:5000"
    env_file: .env
    depends_on:
      - postgres
      - minio
    restart: always

volumes:
  postgres_data:
    labels:
      - "keep=yes"
  minio_data:
    labels:
      - "keep=yes"
